#!/bin/bash
yum update -y
amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
yum install -y httpd mariadb-server git awscli
systemctl start httpd
systemctl enable httpd
cd /tmp && git clone https://github.com/foozy74/aws-ec2-userdata/ 
cp -r /tmp/aws-ec2-userdata/css /var/www/html/
cp index.php /var/www
usermod -a -G apache ec2-user
chown -R ec2-user:apache /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;
echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
